### ISSUE TITLE
Beschrijving

### ISSUE THREAD

**Issue by RobinStut** [MartijnReeuwijk/web-app-from-scratch-18-19#2]
https://github.com/MartijnReeuwijk/web-app-from-scratch-18-19/blob/f90bd0754010f95257fe27c053665b09be706b85/week1/index.html#L12

Misschien kan je meer toelichten wat de informatie is waar je momenteel naar kijkt. Ik zag de je casenumbers gebruikt, misschien is het leuk om daar een soort datum aan te hangen zodat je weet op welke momenten er een stijging is

**Comment by MartijnReeuwijk** [comment]
👌 goed plan zal er even naar gluren

**Comment by MartijnReeuwijk** [comment]
Heb een kleine beschrijving toegevoegd
