### ISSUE TITLE
Use implicit arrow function return?

### ISSUE THREAD

**Issue by maanlamp** [MartijnReeuwijk/web-app-from-scratch-18-19#5]
https://github.com/MartijnReeuwijk/web-app-from-scratch-18-19/blob/7d4558f3cae1df73cc5bdb03832e781c76a6b59a/week1/public/js/app.js#L26-L28

Arrow functions implicitly return the first expression in their bodies.
Consider the following rewrite:
```js
 .then(response => response.json()) 
```

**Comment by MartijnReeuwijk** [comment]
Fixed

**Comment by MartijnReeuwijk** [comment]
Will remember and keep it consistent 👍
